SI-2581-starting-location-off
DIMO-Network/trips-api pull request #29
Opened 2024-04-24 21:37 UTC by Allyson-English

Goal: we assume that in most cases a user is starting their trip from where their previous trip ended. Due to connectivity issues, we might not get a lat/ lon reading when the trip first starts. In this case, if we find that the previous trip start is reasonably close the prior trips end, we want to set these two locations as equivalent. 

### Changes:
- This change adds trip starting latitude and ending latitude (nullable) to the trips table 
- The vehicle trip endpoint checks if the distance between the start location of a new trip is within 0.25 miles of the previous trips end location. If it is, an estimated start location is returned that is equivalent to the prior trips end location. 

### Notes:
- Is 0.25 miles enough to account for both GPS drift and latent connectivity?
- The estimated trip start location will not include a new estimated trip start time (this will have implications for how we're querying and showing the trip on the front end, we'll have to add in the first point after the query)

### TODO:
- tests
- trip window processor must be updated to send location data 

### Example:
``` 
    {
      "id": "trip_3",
      "start": {
        "actual": {
          "time": "2024-04-26T20:13:25Z",
          "latitude": 39.7532714370136,
          "longitude": -105.021651973248
        }
      },
      "end": {
        "actual": {
          "time": "2024-04-26T20:20:25Z",
          "latitude": 39.7623738641497,
          "longitude": -105.020031711881
        }
      }
    },
    {
      "id": "trip_4",
      "start": {
        "estimate": {
          "time": "0001-01-01T00:00:00Z",
          "latitude": 39.7623738641497,
          "longitude": -105.020031711881
        },
        "actual": {
          "time": "2024-04-26T21:13:25Z",
          "latitude": 39.761996569876,
          "longitude": -105.019431418752
        }
      },
      "end": {
        "actual": {
          "time": "2024-04-26T22:20:25Z",
          "latitude": 39.7768130897781,
          "longitude": -105.017106574405
        }
      }
    }

2024-04-24 22:04 UTC, elffjs commented on internal/api/api.go
> +			qm.OrderBy(models.TripColumns.EndTime+" ASC"),
Should we reverse at the end? People love "new at the top", it seems.

2024-04-24 22:05 UTC, elffjs commented on internal/api/api.go
> +			qm.Limit(pageSize),
Should we try to include one extra trip so that we can patch up the earliest returned trip?

2024-04-24 22:05 UTC, elffjs commented
What do you think of patching up the trip right when it starts? Like doing a query right when that start trip event comes in.

2024-05-07 04:10 UTC, elffjs requested changes

2024-05-07 04:10 UTC, elffjs commented on internal/services/consumer/consumer.go
> +			qm.Where(models.TripColumns.EndTime+" IS NOT NULL"),
```suggestion
			models.TripWhere.EndTime.IsNotNull(),
```

2024-05-07 04:10 UTC, elffjs commented on internal/services/consumer/consumer.go
> +	if v.R != nil && len(v.R.VehicleTokenTrips) > 0 {
I wouldn't worry about `v.R` being `nil`.

2024-05-07 04:10 UTC, elffjs commented on internal/services/consumer/consumer.go
> +		if helper.InterpolateTripStart(v.R.VehicleTokenTrips[0].EndPosition, segment.StartPosition) {
What if one or both of these is null?

2024-05-07 04:10 UTC, elffjs commented on internal/services/consumer/consumer.go
> +func pointToDB(longitude, latitude float64) pgeo.Point {
Maybe this should take in a struct or something? I would definitely screw up the order of this, personally.

2024-05-08 16:53 UTC, KevinJoiner requested changes

2024-05-08 16:53 UTC, KevinJoiner commented on internal/helper/tripGeos.go
> +	Trips       []*TripDetails `json:"trips"`
I don't think these need to be pointers.

2024-05-08 16:53 UTC, KevinJoiner commented on internal/services/consumer/consumer.go
> +	if v.R != nil && len(v.R.VehicleTokenTrips) > 0 {
I think we can combine this if statement with the one below.
Also, I'm just curious about how we know `v.R` is not nil. Is this something that boiler guarantees?

2024-05-08 16:53 UTC, KevinJoiner commented on internal/services/consumer/consumer.go
> +		if helper.InterpolateTripStart(v.R.VehicleTokenTrips[0].EndPosition, segment.StartPosition) {
You could add null checks in the Interpolate functions. If you also make VehicleTokenTrips non pointers.

2024-05-08 16:53 UTC, KevinJoiner commented on internal/services/consumer/consumer.go
> +		return fmt.Errorf("error fetching segment %s: %w", event.Data.ID, err)
❤️ Love some good wraps

2024-05-08 16:57 UTC, elffjs commented on cmd/trips-api/main.go
> +		return
Yes, I think that's intentional.

2024-05-08 19:44 UTC, elffjs commented on go.mod
> +	github.com/testcontainers/testcontainers-go v0.30.0
I wish the tool would just to this for you.

2024-05-08 20:02 UTC, elffjs commented on internal/services/consumer/consumer.go
> +	if v.R != nil && len(v.R.VehicleTokenTrips) > 0 {
There's not a ton of documentation. In my experience, `R` is always populated if you do a load.

2024-05-12 05:25 UTC, elffjs commented on internal/helper/tripGeos.go
> +func InterpolateTripStart(prevTripEnd, newTripStart pgeo.NullPoint) bool {
Delete?

2024-05-12 05:26 UTC, elffjs commented on internal/helper/tripGeos.go
> +type VehicleTrips struct {
I'm not sure that these API objects should be here.

2024-05-13 05:19 UTC, elffjs requested changes

2024-05-13 05:19 UTC, elffjs commented on internal/services/consumer/consumer.go
> +		}
It's good that we're not intentionally bailing if this check fails—there's always going to be a first trip—but note that line 143 is probably going to blow up.

2024-05-13 15:59 UTC, elffjs commented on internal/services/consumer/consumer_test.go
> +			ID string "json:\"id\""
Why are the tags escaped here?

2024-05-14 00:04 UTC, elffjs commented
Will give this another pass tonight. Sorry for the delay.

2024-05-14 13:16 UTC, KevinJoiner reviewed
Couple of small comments. My only real comment is about if BeginSegement query works with a vehicle that has no previous trips.

2024-05-14 13:16 UTC, KevinJoiner commented on internal/services/consumer/consumer_test.go
> +			ID string "json:\"id\""
If you use backticks you do not have to escape.
```suggestion
			ID string `json:"id"`
```

2024-05-14 13:16 UTC, KevinJoiner commented on internal/test/helpers.go
> +		return handleContainerStartErr(ctx, errors.Wrap(err, "failed to get container external port"), t)
[github.com/pkg/errors](https://github.com/pkg/errors) has been archived for sometime now since error wrapping was added to the std lib.
```suggestion
		return handleContainerStartErr(ctx, fmt.Errorf("failed to get container external port: %w", err), t)
```

2024-05-14 13:16 UTC, KevinJoiner commented on internal/test/helpers.go
> +		t.Fatal(err)
nit:
```suggestion
		t.Fatalf("start container error: %s", err.Error())
```

2024-05-14 13:32 UTC, elffjs commented on internal/services/consumer/consumer.go
>  			return fmt.Errorf("failed to find vehicle %s: %w", event.Subject, err)
No, only if we don’t find a vehicle.

2024-05-14 13:32 UTC, elffjs commented on internal/services/consumer/consumer.go
>  			return fmt.Errorf("failed to find vehicle %s: %w", event.Subject, err)
A test with no previous trips would be good! I’m not sure if there is one.

2024-05-14 13:49 UTC, elffjs commented on cmd/trips-api/main.go
> +	esStore, err := es_store.New(&settings)
One thing to say is that big, safe-ish, unrelated changes like this I tend to do separate PRs for (or just push to master., I must admit).

2024-05-14 13:56 UTC, elffjs commented on internal/services/consumer/consumer_test.go
> +			TokenID int "json:\"tokenId\""
```suggestion
			TokenID int `json:"tokenId"`
```

2024-05-14 15:34 UTC, elffjs approved these changes

2024-05-14 15:36 UTC, elffjs commented
I think linting is just timing out. Adding the test file back too.

2024-05-14 17:49 UTC, Allyson-English commented on internal/services/consumer/consumer.go
>  			return fmt.Errorf("failed to find vehicle %s: %w", event.Subject, err)
This is included in the tests! The test names are kind of atrocious.. I just went through and added comments describing each of them.

2024-05-14 18:32 UTC, merged